name: Haskell Release Nightly
on:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exeName: chiscord-nightly-linux-x86_64
          # macos and windows doesn't like non-Main.hs???
          # - os: macOS-latest
          #   exeName: chiscord-nightly-darwin-aarch64
          # - os: windows-latest
          #   exeName: chiscord-nightly-windows-x86_64.exe
        
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.12.2'
        cabal-version: '3.14.2.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal new-build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
    - name: Get executable path
      id: get-path
      run: echo "path=$(cabal list-bin chiscord)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.get-path.outputs.path }}
        asset_name: ${{ matrix.exeName }}
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: true